/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ProductPromotion } from "./ProductPromotion";
import { ProductPromotionCountArgs } from "./ProductPromotionCountArgs";
import { ProductPromotionFindManyArgs } from "./ProductPromotionFindManyArgs";
import { ProductPromotionFindUniqueArgs } from "./ProductPromotionFindUniqueArgs";
import { DeleteProductPromotionArgs } from "./DeleteProductPromotionArgs";
import { ProductPromotionService } from "../productPromotion.service";
@graphql.Resolver(() => ProductPromotion)
export class ProductPromotionResolverBase {
  constructor(protected readonly service: ProductPromotionService) {}

  async _productPromotionsMeta(
    @graphql.Args() args: ProductPromotionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ProductPromotion])
  async productPromotions(
    @graphql.Args() args: ProductPromotionFindManyArgs
  ): Promise<ProductPromotion[]> {
    return this.service.productPromotions(args);
  }

  @graphql.Query(() => ProductPromotion, { nullable: true })
  async productPromotion(
    @graphql.Args() args: ProductPromotionFindUniqueArgs
  ): Promise<ProductPromotion | null> {
    const result = await this.service.productPromotion(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ProductPromotion)
  async deleteProductPromotion(
    @graphql.Args() args: DeleteProductPromotionArgs
  ): Promise<ProductPromotion | null> {
    try {
      return await this.service.deleteProductPromotion(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
