/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  ProductPromotion as PrismaProductPromotion,
} from "@prisma/client";

export class ProductPromotionServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.ProductPromotionCountArgs, "select">
  ): Promise<number> {
    return this.prisma.productPromotion.count(args);
  }

  async productPromotions<T extends Prisma.ProductPromotionFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.ProductPromotionFindManyArgs>
  ): Promise<PrismaProductPromotion[]> {
    return this.prisma.productPromotion.findMany<Prisma.ProductPromotionFindManyArgs>(
      args
    );
  }
  async productPromotion<T extends Prisma.ProductPromotionFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.ProductPromotionFindUniqueArgs>
  ): Promise<PrismaProductPromotion | null> {
    return this.prisma.productPromotion.findUnique(args);
  }
  async createProductPromotion<T extends Prisma.ProductPromotionCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ProductPromotionCreateArgs>
  ): Promise<PrismaProductPromotion> {
    return this.prisma.productPromotion.create<T>(args);
  }
  async updateProductPromotion<T extends Prisma.ProductPromotionUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ProductPromotionUpdateArgs>
  ): Promise<PrismaProductPromotion> {
    return this.prisma.productPromotion.update<T>(args);
  }
  async deleteProductPromotion<T extends Prisma.ProductPromotionDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.ProductPromotionDeleteArgs>
  ): Promise<PrismaProductPromotion> {
    return this.prisma.productPromotion.delete(args);
  }
}
