/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Refund } from "./Refund";
import { RefundCountArgs } from "./RefundCountArgs";
import { RefundFindManyArgs } from "./RefundFindManyArgs";
import { RefundFindUniqueArgs } from "./RefundFindUniqueArgs";
import { DeleteRefundArgs } from "./DeleteRefundArgs";
import { RefundService } from "../refund.service";
@graphql.Resolver(() => Refund)
export class RefundResolverBase {
  constructor(protected readonly service: RefundService) {}

  async _refundsMeta(
    @graphql.Args() args: RefundCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Refund])
  async refunds(@graphql.Args() args: RefundFindManyArgs): Promise<Refund[]> {
    return this.service.refunds(args);
  }

  @graphql.Query(() => Refund, { nullable: true })
  async refund(
    @graphql.Args() args: RefundFindUniqueArgs
  ): Promise<Refund | null> {
    const result = await this.service.refund(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Refund)
  async deleteRefund(
    @graphql.Args() args: DeleteRefundArgs
  ): Promise<Refund | null> {
    try {
      return await this.service.deleteRefund(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
