/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { WishlistItem } from "./WishlistItem";
import { WishlistItemCountArgs } from "./WishlistItemCountArgs";
import { WishlistItemFindManyArgs } from "./WishlistItemFindManyArgs";
import { WishlistItemFindUniqueArgs } from "./WishlistItemFindUniqueArgs";
import { DeleteWishlistItemArgs } from "./DeleteWishlistItemArgs";
import { WishlistItemService } from "../wishlistItem.service";
@graphql.Resolver(() => WishlistItem)
export class WishlistItemResolverBase {
  constructor(protected readonly service: WishlistItemService) {}

  async _wishlistItemsMeta(
    @graphql.Args() args: WishlistItemCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [WishlistItem])
  async wishlistItems(
    @graphql.Args() args: WishlistItemFindManyArgs
  ): Promise<WishlistItem[]> {
    return this.service.wishlistItems(args);
  }

  @graphql.Query(() => WishlistItem, { nullable: true })
  async wishlistItem(
    @graphql.Args() args: WishlistItemFindUniqueArgs
  ): Promise<WishlistItem | null> {
    const result = await this.service.wishlistItem(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => WishlistItem)
  async deleteWishlistItem(
    @graphql.Args() args: DeleteWishlistItemArgs
  ): Promise<WishlistItem | null> {
    try {
      return await this.service.deleteWishlistItem(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
