/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ProductGenre } from "./ProductGenre";
import { ProductGenreCountArgs } from "./ProductGenreCountArgs";
import { ProductGenreFindManyArgs } from "./ProductGenreFindManyArgs";
import { ProductGenreFindUniqueArgs } from "./ProductGenreFindUniqueArgs";
import { DeleteProductGenreArgs } from "./DeleteProductGenreArgs";
import { ProductGenreService } from "../productGenre.service";
@graphql.Resolver(() => ProductGenre)
export class ProductGenreResolverBase {
  constructor(protected readonly service: ProductGenreService) {}

  async _productGenresMeta(
    @graphql.Args() args: ProductGenreCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ProductGenre])
  async productGenres(
    @graphql.Args() args: ProductGenreFindManyArgs
  ): Promise<ProductGenre[]> {
    return this.service.productGenres(args);
  }

  @graphql.Query(() => ProductGenre, { nullable: true })
  async productGenre(
    @graphql.Args() args: ProductGenreFindUniqueArgs
  ): Promise<ProductGenre | null> {
    const result = await this.service.productGenre(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ProductGenre)
  async deleteProductGenre(
    @graphql.Args() args: DeleteProductGenreArgs
  ): Promise<ProductGenre | null> {
    try {
      return await this.service.deleteProductGenre(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
