/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AppCoupons } from "./AppCoupons";
import { AppCouponsCountArgs } from "./AppCouponsCountArgs";
import { AppCouponsFindManyArgs } from "./AppCouponsFindManyArgs";
import { AppCouponsFindUniqueArgs } from "./AppCouponsFindUniqueArgs";
import { DeleteAppCouponsArgs } from "./DeleteAppCouponsArgs";
import { AppCouponsService } from "../appCoupons.service";
@graphql.Resolver(() => AppCoupons)
export class AppCouponsResolverBase {
  constructor(protected readonly service: AppCouponsService) {}

  async _appCouponsItemsMeta(
    @graphql.Args() args: AppCouponsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [AppCoupons])
  async appCouponsItems(
    @graphql.Args() args: AppCouponsFindManyArgs
  ): Promise<AppCoupons[]> {
    return this.service.appCouponsItems(args);
  }

  @graphql.Query(() => AppCoupons, { nullable: true })
  async appCoupons(
    @graphql.Args() args: AppCouponsFindUniqueArgs
  ): Promise<AppCoupons | null> {
    const result = await this.service.appCoupons(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AppCoupons)
  async deleteAppCoupons(
    @graphql.Args() args: DeleteAppCouponsArgs
  ): Promise<AppCoupons | null> {
    try {
      return await this.service.deleteAppCoupons(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
