/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ShopCoupons } from "./ShopCoupons";
import { ShopCouponsCountArgs } from "./ShopCouponsCountArgs";
import { ShopCouponsFindManyArgs } from "./ShopCouponsFindManyArgs";
import { ShopCouponsFindUniqueArgs } from "./ShopCouponsFindUniqueArgs";
import { DeleteShopCouponsArgs } from "./DeleteShopCouponsArgs";
import { ShopCouponsService } from "../shopCoupons.service";
@graphql.Resolver(() => ShopCoupons)
export class ShopCouponsResolverBase {
  constructor(protected readonly service: ShopCouponsService) {}

  async _shopCouponsItemsMeta(
    @graphql.Args() args: ShopCouponsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ShopCoupons])
  async shopCouponsItems(
    @graphql.Args() args: ShopCouponsFindManyArgs
  ): Promise<ShopCoupons[]> {
    return this.service.shopCouponsItems(args);
  }

  @graphql.Query(() => ShopCoupons, { nullable: true })
  async shopCoupons(
    @graphql.Args() args: ShopCouponsFindUniqueArgs
  ): Promise<ShopCoupons | null> {
    const result = await this.service.shopCoupons(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ShopCoupons)
  async deleteShopCoupons(
    @graphql.Args() args: DeleteShopCouponsArgs
  ): Promise<ShopCoupons | null> {
    try {
      return await this.service.deleteShopCoupons(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
