/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Promotions } from "./Promotions";
import { PromotionsCountArgs } from "./PromotionsCountArgs";
import { PromotionsFindManyArgs } from "./PromotionsFindManyArgs";
import { PromotionsFindUniqueArgs } from "./PromotionsFindUniqueArgs";
import { DeletePromotionsArgs } from "./DeletePromotionsArgs";
import { PromotionsService } from "../promotions.service";
@graphql.Resolver(() => Promotions)
export class PromotionsResolverBase {
  constructor(protected readonly service: PromotionsService) {}

  async _promotionsItemsMeta(
    @graphql.Args() args: PromotionsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Promotions])
  async promotionsItems(
    @graphql.Args() args: PromotionsFindManyArgs
  ): Promise<Promotions[]> {
    return this.service.promotionsItems(args);
  }

  @graphql.Query(() => Promotions, { nullable: true })
  async promotions(
    @graphql.Args() args: PromotionsFindUniqueArgs
  ): Promise<Promotions | null> {
    const result = await this.service.promotions(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Promotions)
  async deletePromotions(
    @graphql.Args() args: DeletePromotionsArgs
  ): Promise<Promotions | null> {
    try {
      return await this.service.deletePromotions(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
