/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  CourierCategory as PrismaCourierCategory,
} from "@prisma/client";

export class CourierCategoryServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.CourierCategoryCountArgs, "select">
  ): Promise<number> {
    return this.prisma.courierCategory.count(args);
  }

  async courierCategories<T extends Prisma.CourierCategoryFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.CourierCategoryFindManyArgs>
  ): Promise<PrismaCourierCategory[]> {
    return this.prisma.courierCategory.findMany<Prisma.CourierCategoryFindManyArgs>(
      args
    );
  }
  async courierCategory<T extends Prisma.CourierCategoryFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.CourierCategoryFindUniqueArgs>
  ): Promise<PrismaCourierCategory | null> {
    return this.prisma.courierCategory.findUnique(args);
  }
  async createCourierCategory<T extends Prisma.CourierCategoryCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.CourierCategoryCreateArgs>
  ): Promise<PrismaCourierCategory> {
    return this.prisma.courierCategory.create<T>(args);
  }
  async updateCourierCategory<T extends Prisma.CourierCategoryUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.CourierCategoryUpdateArgs>
  ): Promise<PrismaCourierCategory> {
    return this.prisma.courierCategory.update<T>(args);
  }
  async deleteCourierCategory<T extends Prisma.CourierCategoryDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.CourierCategoryDeleteArgs>
  ): Promise<PrismaCourierCategory> {
    return this.prisma.courierCategory.delete(args);
  }
}
