/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CourierCategory } from "./CourierCategory";
import { CourierCategoryCountArgs } from "./CourierCategoryCountArgs";
import { CourierCategoryFindManyArgs } from "./CourierCategoryFindManyArgs";
import { CourierCategoryFindUniqueArgs } from "./CourierCategoryFindUniqueArgs";
import { DeleteCourierCategoryArgs } from "./DeleteCourierCategoryArgs";
import { CourierCategoryService } from "../courierCategory.service";
@graphql.Resolver(() => CourierCategory)
export class CourierCategoryResolverBase {
  constructor(protected readonly service: CourierCategoryService) {}

  async _courierCategoriesMeta(
    @graphql.Args() args: CourierCategoryCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [CourierCategory])
  async courierCategories(
    @graphql.Args() args: CourierCategoryFindManyArgs
  ): Promise<CourierCategory[]> {
    return this.service.courierCategories(args);
  }

  @graphql.Query(() => CourierCategory, { nullable: true })
  async courierCategory(
    @graphql.Args() args: CourierCategoryFindUniqueArgs
  ): Promise<CourierCategory | null> {
    const result = await this.service.courierCategory(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CourierCategory)
  async deleteCourierCategory(
    @graphql.Args() args: DeleteCourierCategoryArgs
  ): Promise<CourierCategory | null> {
    try {
      return await this.service.deleteCourierCategory(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
