/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Complaints } from "./Complaints";
import { ComplaintsCountArgs } from "./ComplaintsCountArgs";
import { ComplaintsFindManyArgs } from "./ComplaintsFindManyArgs";
import { ComplaintsFindUniqueArgs } from "./ComplaintsFindUniqueArgs";
import { DeleteComplaintsArgs } from "./DeleteComplaintsArgs";
import { ComplaintsService } from "../complaints.service";
@graphql.Resolver(() => Complaints)
export class ComplaintsResolverBase {
  constructor(protected readonly service: ComplaintsService) {}

  async _complaintsItemsMeta(
    @graphql.Args() args: ComplaintsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Complaints])
  async complaintsItems(
    @graphql.Args() args: ComplaintsFindManyArgs
  ): Promise<Complaints[]> {
    return this.service.complaintsItems(args);
  }

  @graphql.Query(() => Complaints, { nullable: true })
  async complaints(
    @graphql.Args() args: ComplaintsFindUniqueArgs
  ): Promise<Complaints | null> {
    const result = await this.service.complaints(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Complaints)
  async deleteComplaints(
    @graphql.Args() args: DeleteComplaintsArgs
  ): Promise<Complaints | null> {
    try {
      return await this.service.deleteComplaints(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
