/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { MainCategory } from "./MainCategory";
import { MainCategoryCountArgs } from "./MainCategoryCountArgs";
import { MainCategoryFindManyArgs } from "./MainCategoryFindManyArgs";
import { MainCategoryFindUniqueArgs } from "./MainCategoryFindUniqueArgs";
import { DeleteMainCategoryArgs } from "./DeleteMainCategoryArgs";
import { MainCategoryService } from "../mainCategory.service";
@graphql.Resolver(() => MainCategory)
export class MainCategoryResolverBase {
  constructor(protected readonly service: MainCategoryService) {}

  async _mainCategoriesMeta(
    @graphql.Args() args: MainCategoryCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [MainCategory])
  async mainCategories(
    @graphql.Args() args: MainCategoryFindManyArgs
  ): Promise<MainCategory[]> {
    return this.service.mainCategories(args);
  }

  @graphql.Query(() => MainCategory, { nullable: true })
  async mainCategory(
    @graphql.Args() args: MainCategoryFindUniqueArgs
  ): Promise<MainCategory | null> {
    const result = await this.service.mainCategory(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => MainCategory)
  async deleteMainCategory(
    @graphql.Args() args: DeleteMainCategoryArgs
  ): Promise<MainCategory | null> {
    try {
      return await this.service.deleteMainCategory(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
