/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { MainCategoryService } from "../mainCategory.service";
import { MainCategoryCreateInput } from "./MainCategoryCreateInput";
import { MainCategory } from "./MainCategory";
import { MainCategoryFindManyArgs } from "./MainCategoryFindManyArgs";
import { MainCategoryWhereUniqueInput } from "./MainCategoryWhereUniqueInput";
import { MainCategoryUpdateInput } from "./MainCategoryUpdateInput";

export class MainCategoryControllerBase {
  constructor(protected readonly service: MainCategoryService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: MainCategory })
  async createMainCategory(
    @common.Body() data: MainCategoryCreateInput
  ): Promise<MainCategory> {
    return await this.service.createMainCategory({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [MainCategory] })
  @ApiNestedQuery(MainCategoryFindManyArgs)
  async mainCategories(
    @common.Req() request: Request
  ): Promise<MainCategory[]> {
    const args = plainToClass(MainCategoryFindManyArgs, request.query);
    return this.service.mainCategories({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: MainCategory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async mainCategory(
    @common.Param() params: MainCategoryWhereUniqueInput
  ): Promise<MainCategory | null> {
    const result = await this.service.mainCategory({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: MainCategory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateMainCategory(
    @common.Param() params: MainCategoryWhereUniqueInput,
    @common.Body() data: MainCategoryUpdateInput
  ): Promise<MainCategory | null> {
    try {
      return await this.service.updateMainCategory({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: MainCategory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteMainCategory(
    @common.Param() params: MainCategoryWhereUniqueInput
  ): Promise<MainCategory | null> {
    try {
      return await this.service.deleteMainCategory({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
